### ISSUE TITLE
Produce a predict python executable for testing the model 

### ISSUE THREAD

**Issue by szingaro** [spaces-team/doctor#1]
Given the following `input`:
- a `data.csv` file containing data from the student.

We provide the `output`:
- a `result.csv` file containing the predicted class and the accuracy.

**Comment by francevska** [comment]
I fulfilled the task but the output is a .txt file, not a .csv.

**Comment by szingaro** [comment]
To have a csv file would be great for integration in pipeline of this tool. It should be enough to rename the file in the script that outputs it.
