### ISSUE TITLE
Write a README file with proper description

### ISSUE THREAD

**Issue by szingaro** [spaces-team/doctor#2]
@francevska please provide a useful description of the project in order to let other know how does it works.

**Comment by szingaro** [comment]
I uploaded a template to ease the writing. This is the [commit](https://github.com/spaces-team/doc/commit/6b4d2ef6cc60c5da4c326c7254e356d83e9e86ac)

**Comment by francevska** [comment]
I uploaded the README. Please check if it is ok.

**Comment by szingaro** [comment]
Is it possible to move etichette.xls to doc folder and link it in the readme file so to be cliccable ? moreover, it would be great to have instructions on how to use the standalone version of the tool, with data provided by the user.
